#Variables globales
variables:
  APP_VERSION: "1.0"
  FRONTEND_PATH: "./webapp"

#Etapes dans notre CI/CD
stages:
  #CI
  - build_front
  - build_back
  #CD
  - deploy

cache:
  paths:
    - ${FRONTEND_PATH}/node_modules

build_front:
  only:
    - master
  stage: build_front
  before_script:
    - cd ${FRONTEND_PATH}
    - ls -l
  script:
    - npm install
    - npm run deployapp
  after_script:
    - cd ..

build_back:
  only:
    - master
  stage: build_back
  script:
    - mvn clean install
  after_script:
    - cp ./target/demo-0.0.1-SNAPSHOT.jar /data/demo-0.0.1-SNAPSHOT.jar

deploy:
  only:
    - master
  stage: deploy
  script:
    #Lance le jar
    - ls -l /data
    - sudo systemctl stop ez-debate.service
    - sudo systemctl start ez-debate.service
