#Variables globales
variables:
  APP_VERSION: "1.0"
  FRONTEND_PATH: "./webapp"

#Etapes dans notre CI/CD
stages:
  #CI
  - build
  #CD
  - deploy

cache:
  paths:
    - ${FRONTEND_PATH}/node_modules

build:
  only:
    - master
  stage: build
  before_script:
    - cd ${FRONTEND_PATH}
    - ls -l
  script:
    #Telecharger les dépendances
    - npm install
    #Genere les fichiers statiques et copie le tout dans /resources/static de springboot
    - npm run deployapp
    #On retourne dans le projet mvn
    - cd ..
    #Genere le jar dans /target
    - mvn clean install
    - ls -l ./target/
    - cp -r ./target/demo-0.0.1-SNAPSHOT.jar /data/demo-0.0.1-SNAPSHOT.jar
    - ls -l /data

deploy:
  only:
    - master
  stage: deploy
  script:
    #Lance le jar
    - ls -l /data
    - sudo systemctl stop ez-debate.service
    - sudo systemctl start ez-debate.service
